name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: false
          browser: chrome
          headed: false
          publish-summary: true

      # 5️⃣ Upload Cypress screenshots (always, even if tests fail)
      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      # 6️⃣ Upload Cypress videos (always, even if tests fail)
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/

      # 7️⃣ Optional: Upload Cypress logs for debugging
      - name: Upload Cypress logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-logs
          path: cypress/logs/

      # 8️⃣ Fail CI if any tests failed
      - name: Fail CI on Cypress test failures
        if: failure()
        run: |
          echo "⚠️ Cypress tests failed. Check screenshots and videos for details."
          exit 1
