name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: false
          browser: chrome
          headed: false
          component: false
          publish-summary: true

      # 5️⃣ Upload Cypress videos
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/

      # 6️⃣ Upload Cypress screenshots
      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      # 7️⃣ Handle exit code for known bugs
      - name: Check Cypress exit code
        if: always()
        run: |
          echo "⚠️ Cypress run finished."
          if [ -f cypress/results/failed-known-bugs.txt ]; then
            echo "Known bugs failed. CI will pass, check report for details."
          else
            echo "Other failures detected. CI will fail."
            exit 1
